CREATE TABLE inventario (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR(150) NOT NULL,
    produto VARCHAR(100) NOT NULL
);

INSERT INTO inventario (id, nome, produto) VALUES
(1, 'Helena Silva', 'Placa de Vídeo RTX 3060'),
(2, 'Thiago Pereira', 'Suporte para Notebook'),
(3, 'Igor Mendes', 'Mouse Sem Fio Dell'),
(4, 'Fernanda Vieira', 'SSD M.2 NVMe 1TB Kingston'),
(5, 'Carlos Silva', 'Teclado Mecânico Logitech'),
(6, 'Oliveira Pereira', 'Tablet Apple iPad'),
(7, 'Bruno Fernandes', 'Webcam Logitech C920'),
(8, 'Gustavo Pereira', 'Luminária de Mesa LED'),
(9, 'Thiago Silva', 'Memória RAM 16GB DDR4'),
(10, 'Lucas Nascimento', 'SSD M.2 NVMe 1TB Kingston'),
(11, 'Beatriz Lima', 'Cadeira Ergonômica Flexform'),
(12, 'Oliveira Costa', 'Mouse Sem Fio Dell'),
(13, 'Fernanda Martins', 'Mouse Sem Fio Dell'),
(14, 'Caio Ribeiro', 'Carregador Indutivo Sem Fio'),
(15, 'Sofia Santos', 'Placa de Vídeo RTX 3060'),
(16, 'João Fernandes', 'Mouse Sem Fio Dell'),
(17, 'Elisa Oliveira', 'Impressora HP DeskJet'),
(18, 'Vanessa Rocha', 'Carregador Indutivo Sem Fio'),
(19, 'Diego Vieira', 'Webcam Logitech C920'),
(20, 'Eduardo Santos', 'Gabinete ATX Gamer'),
(21, 'Patricia Gomes', 'Teclado Mecânico Logitech'),
(22, 'Patricia Souza', 'Nobreak Intelbras 1200VA'),
(23, 'Thiago Almeida', 'Caixa de Som JBL Flip'),
(24, 'Diego Ferreira', 'Hub USB-C 7 em 1'),
(25, 'Caio Alves', 'Gabinete ATX Gamer'),
(26, 'Thiago Nascimento', 'Gabinete ATX Gamer'),
(27, 'Eduardo Barbosa', 'Caixa de Som JBL Flip'),
(28, 'Lucas Fernandes', 'Placa de Vídeo RTX 3060'),
(29, 'Rafael Ferreira', 'Luminária de Mesa LED'),
(30, 'Elisa Lima', 'Caixa de Som JBL Flip'),
(31, 'Patricia Dias', 'Mesa Digitalizadora Wacom'),
(32, 'Daniela Pereira', 'Microfone Condensador Redragon'),
(33, 'Carlos Costa', 'Nobreak Intelbras 1200VA'),
(34, 'Thiago Oliveira', 'Webcam Logitech C920'),
(35, 'Aline Alves', 'Caixa de Som JBL Flip'),
(36, 'Matheus Martins', 'Caixa de Som JBL Flip'),
(37, 'João Rodrigues', 'Filtro de Linha 6 Tomadas'),
(38, 'Igor Pereira', 'Placa de Vídeo RTX 3060'),
(39, 'Sofia Mendes', 'Roteador TP-Link Wi-Fi 6'),
(40, 'Heitor Vieira', 'Nobreak Intelbras 1200VA'),
(41, 'Diego Pereira', 'Cadeira Ergonômica Flexform'),
(42, 'Matheus Oliveira', 'Memória RAM 16GB DDR4'),
(43, 'Daniela Souza', 'Cadeira Ergonômica Flexform'),
(44, 'Lucas Dias', 'SSD M.2 NVMe 1TB Kingston'),
(45, 'Eduardo Martins', 'Nobreak Intelbras 1200VA'),
(46, 'João Soares', 'Filtro de Linha 6 Tomadas'),
(47, 'Ana Dias', 'Placa de Vídeo RTX 3060'),
(48, 'Helena Dias', 'Impressora HP DeskJet'),
(49, 'Thiago Rocha', 'Mesa Digitalizadora Wacom'),
(50, 'Helena Gomes', 'SSD M.2 NVMe 1TB Kingston'),
(51, 'Lucas Almeida', 'Notebook Dell Inspiron'),
(52, 'Sofia Soares', 'Memória RAM 16GB DDR4'),
(53, 'Mariana Soares', 'Mouse Sem Fio Dell'),
(54, 'Wagner Rocha', 'Tablet Apple iPad'),
(55, 'Nicolas Rodrigues', 'Hub USB-C 7 em 1'),
(56, 'Lucas Fernandes', 'Memória RAM 16GB DDR4'),
(57, 'Ana Barbosa', 'Mesa Digitalizadora Wacom'),
(58, 'Matheus Silva', 'Mouse Sem Fio Dell'),
(59, 'Diego Gomes', 'Suporte para Notebook'),
(60, 'Daniela Pereira', 'Roteador TP-Link Wi-Fi 6'),
(61, 'Fernanda Oliveira', 'Placa de Vídeo RTX 3060'),
(62, 'Matheus Oliveira', 'Memória RAM 16GB DDR4'),
(63, 'Igor Rodrigues', 'Gabinete ATX Gamer'),
(64, 'Lara Fernandes', 'Headset HyperX Cloud II'),
(65, 'Sofia Soares', 'Carregador Indutivo Sem Fio'),
(66, 'Heitor Alves', 'Impressora HP DeskJet'),
(67, 'Nicolas Nascimento', 'HD Externo Toshiba 1TB'),
(68, 'Felipe Dias', 'Caixa de Som JBL Flip'),
(69, 'Diego Almeida', 'Tablet Apple iPad'),
(70, 'Isabela Souza', 'Suporte para Notebook'),
(71, 'Patricia Oliveira', 'Mesa Digitalizadora Wacom'),
(72, 'Bruno Vieira', 'Impressora HP DeskJet'),
(73, 'Patricia Vieira', 'Suporte para Notebook'),
(74, 'Ana Oliveira', 'Fonte Corsair 650W'),
(75, 'Daniela Pereira', 'Teclado Mecânico Logitech'),
(76, 'Carlos Costa', 'Teclado Mecânico Logitech'),
(77, 'Rafael Lima', 'Gabinete ATX Gamer'),
(78, 'Matheus Alves', 'Impressora HP DeskJet'),
('79', 'Igor Mendes', 'Roteador TP-Link Wi-Fi 6'),
(80, 'Lara Pereira', 'Placa Mãe Asus TUF'),
(81, 'Lara Carvalho', 'Webcam Logitech C920'),
(82, 'Gabriel Souza', 'Gabinete ATX Gamer'),
(83, 'Heitor Ribeiro', 'SSD M.2 NVMe 1TB Kingston'),
(84, 'Gustavo Almeida', 'Placa de Vídeo RTX 3060'),
(85, 'Daniela Dias', 'Caixa de Som JBL Flip'),
(86, 'Gabriel Santos', 'Nobreak Intelbras 1200VA'),
(87, 'Beatriz Souza', 'Suporte para Notebook'),
(88, 'Nicolas Alves', 'Impressora HP DeskJet'),
(89, 'Isabela Rodrigues', 'SSD M.2 NVMe 1TB Kingston'),
(90, 'Mariana Lima', 'Luminária de Mesa LED'),
(91, 'Rafael Oliveira', 'Luminária de Mesa LED'),
(92, 'Gabriel Santos', 'Caixa de Som JBL Flip'),
(93, 'Ana Oliveira', 'Memória RAM 16GB DDR4'),
(94, 'Rafael Ferreira', 'SSD M.2 NVMe 1TB Kingston'),
(95, 'Matheus Lopes', 'Webcam Logitech C920'),
(96, 'Felipe Santos', 'Headset HyperX Cloud II'),
(97, 'Elisa Silva', 'Nobreak Intelbras 1200VA'),
(98, 'Sofia Almeida', 'HD Externo Toshiba 1TB'),
(99, 'Heitor Nascimento', 'Placa de Vídeo RTX 3060'),
(100, 'Matheus Rodrigues', 'Webcam Logitech C920'),
(101, 'Vanessa Alves', 'Monitor LG 29 Ultrawide'),
(102, 'Daniela Mendes', 'Mesa Digitalizadora Wacom'),
(103, 'Daniela Santos', 'Roteador TP-Link Wi-Fi 6'),
(104, 'Lara Soares', 'Tablet Apple iPad'),
(105, 'Lucas Santos', 'Tablet Apple iPad'),
(106, 'Fernanda Ferreira', 'Teclado Mecânico Logitech'),
(107, 'Eduardo Dias', 'Suporte para Notebook'),
(108, 'Felipe Souza', 'Roteador TP-Link Wi-Fi 6'),
(109, 'Rafael Vieira', 'Carregador Indutivo Sem Fio'),
(110, 'Carlos Barbosa', 'Teclado Mecânico Logitech'),
(111, 'Gustavo Dias', 'Roteador TP-Link Wi-Fi 6'),
(112, 'Aline Lima', 'Webcam Logitech C920'),
(113, 'Aline Pereira', 'Filtro de Linha 6 Tomadas'),
(114, 'Felipe Rodrigues', 'Gabinete ATX Gamer'),
(115, 'Wagner Almeida', 'Mesa Digitalizadora Wacom'),
(116, 'Eduardo Silva', 'Luminária de Mesa LED'),
(117, 'Gabriel Oliveira', 'Impressora HP DeskJet'),
(118, 'Oliveira Soares', 'Filtro de Linha 6 Tomadas'),
(119, 'Igor Ribeiro', 'Teclado Mecânico Logitech'),
(120, 'Rafael Ribeiro', 'HD Externo Toshiba 1TB'),
(121, 'Lucas Almeida', 'Microfone Condensador Redragon'),
(122, 'Wagner Barbosa', 'Placa Mãe Asus TUF'),
(123, 'Ana Dias', 'Microfone Condensador Redragon'),
(124, 'Wagner Dias', 'Mouse Sem Fio Dell'),
(125, 'Igor Lima', 'Mouse Sem Fio Dell'),
(126, 'Gabriel Mendes', 'Impressora HP DeskJet'),
(127, 'Juliana Lima', 'HD Externo Toshiba 1TB'),
(128, 'Oliveira Nascimento', 'Mesa Digitalizadora Wacom'),
(129, 'Oliveira Dias', 'Caixa de Som JBL Flip'),
(130, 'Sofia Soares', 'Smartphone Samsung Galaxy'),
(131, 'Sofia Santos', 'Teclado Mecânico Logitech'),
(132, 'Heitor Lima', 'Monitor LG 29 Ultrawide'),
(133, 'Ana Costa', 'Memória RAM 16GB DDR4'),
(134, 'Igor Rocha', 'Filtro de Linha 6 Tomadas'),
(135, 'Lucas Mendes', 'Luminária de Mesa LED'),
(136, 'Heitor Fernandes', 'Notebook Dell Inspiron'),
(137, 'Helena Oliveira', 'Fonte Corsair 650W'),
(138, 'Juliana Fernandes', 'Monitor LG 29 Ultrawide'),
(139, 'Diego Vieira', 'Impressora HP DeskJet'),
(140, 'Juliana Carvalho', 'Cadeira Ergonômica Flexform'),
(141, 'Carlos Gomes', 'Hub USB-C 7 em 1'),
(142, 'Carlos Ribeiro', 'Webcam Logitech C920'),
(143, 'Rafael Dias', 'Mouse Sem Fio Dell'),
(144, 'Caio Fernandes', 'SSD M.2 NVMe 1TB Kingston'),
(145, 'Juliana Pereira', 'Headset HyperX Cloud II'),
(146, 'Mariana Carvalho', 'Notebook Dell Inspiron'),
(147, 'Mariana Mendes', 'Mesa Digitalizadora Wacom'),
(148, 'Gustavo Dias', 'Placa de Vídeo RTX 3060'),
(149, 'Rafael Lima', 'Headset HyperX Cloud II'),
(150, 'Gabriel Martins', 'Monitor LG 29 Ultrawide'),
(151, 'Lara Pereira', 'Webcam Logitech C920'),
(152, 'João Ribeiro', 'HD Externo Toshiba 1TB'),
(153, 'Patricia Pereira', 'Notebook Dell Inspiron'),
(154, 'Nicolas Martins', 'Mesa Digitalizadora Wacom'),
(155, 'Thiago Oliveira', 'Memória RAM 16GB DDR4'),
(156, 'Thiago Ribeiro', 'Caixa de Som JBL Flip'),
(157, 'Felipe Dias', 'Microfone Condensador Redragon'),
(158, 'Beatriz Silva', 'Mouse Sem Fio Dell'),
(159, 'Sofia Ferreira', 'Roteador TP-Link Wi-Fi 6'),
(160, 'Sofia Santos', 'Mouse Sem Fio Dell'),
(161, 'Heitor Ribeiro', 'Placa de Vídeo RTX 3060'),
(162, 'Aline Carvalho', 'Carregador Indutivo Sem Fio'),
(163, 'Helena Martins', 'Roteador TP-Link Wi-Fi 6'),
(164, 'Nicolas Lima', 'Monitor LG 29 Ultrawide'),
(165, 'Heitor Silva', 'Tablet Apple iPad'),
(166, 'Nicolas Ribeiro', 'SSD M.2 NVMe 1TB Kingston'),
(167, 'Eduardo Dias', 'Mesa Digitalizadora Wacom'),
(168, 'Aline Dias', 'Mouse Sem Fio Dell'),
(169, 'Wagner Soares', 'HD Externo Toshiba 1TB'),
(170, 'Gustavo Costa', 'Nobreak Intelbras 1200VA'),
(171, 'Vanessa Fernandes', 'Cadeira Ergonômica Flexform'),
(172, 'Nicolas Carvalho', 'Gabinete ATX Gamer'),
(173, 'Elisa Dias', 'Placa de Vídeo RTX 3060'),
(174, 'Mariana Barbosa', 'Roteador TP-Link Wi-Fi 6'),
(175, 'Wagner Martins', 'Impressora HP DeskJet'),
(176, 'Ana Gomes', 'HD Externo Toshiba 1TB'),
(177, 'Oliveira Carvalho', 'Placa Mãe Asus TUF'),
(178, 'Aline Almeida', 'Luminária de Mesa LED'),
(179, 'Isabela Dias', 'Webcam Logitech C920'),
(180, 'Lara Mendes', 'Headset HyperX Cloud II'),
(181, 'Fernanda Gomes', 'Tablet Apple iPad'),
(182, 'Beatriz Oliveira', 'Microfone Condensador Redragon'),
(183, 'Rafael Dias', 'HD Externo Toshiba 1TB'),
(184, 'Patricia Alves', 'Cadeira Ergonômica Flexform'),
(185, 'Bruno Santos', 'Suporte para Notebook'),
(186, 'Lara Barbosa', 'Memória RAM 16GB DDR4'),
(187, 'Eduardo Almeida', 'SSD M.2 NVMe 1TB Kingston'),
(188, 'Nicolas Nascimento', 'Fonte Corsair 650W'),
(189, 'Elisa Lopes', 'Nobreak Intelbras 1200VA'),
(190, 'Rafael Rodrigues', 'Caixa de Som JBL Flip'),
(191, 'Ana Souza', 'Memória RAM 16GB DDR4'),
(192, 'Heitor Pereira', 'Headset HyperX Cloud II'),
(193, 'João Santos', 'Impressora HP DeskJet'),
(194, 'Rafael Souza', 'Luminária de Mesa LED'),
(195, 'Igor Almeida', 'Gabinete ATX Gamer'),
(196, 'Aline Almeida', 'Carregador Indutivo Sem Fio'),
(197, 'Heitor Fernandes', 'Luminária de Mesa LED'),
(198, 'Lucas Mendes', 'Smartphone Samsung Galaxy'),
(199, 'Isabela Lima', 'Memória RAM 16GB DDR4'),
(200, 'Rafael Rocha', 'Filtro de Linha 6 Tomadas'),
(201, 'Matheus Rocha', 'Suporte para Notebook'),
(202, 'Thiago Almeida', 'Teclado Mecânico Logitech'),
(203, 'Vanessa Pereira', 'Filtro de Linha 6 Tomadas'),
(204, 'Beatriz Costa', 'Impressora HP DeskJet'),
(205, 'Fernanda Rodrigues', 'Cadeira Ergonômica Flexform'),
(206, 'Patricia Martins', 'Fonte Corsair 650W'),
(207, 'Juliana Nascimento', 'Webcam Logitech C920'),
(208, 'Eduardo Carvalho', 'SSD M.2 NVMe 1TB Kingston'),
(209, 'Beatriz Fernandes', 'Luminária de Mesa LED'),
(210, 'Gustavo Santos', 'Webcam Logitech C920'),
(211, 'Gustavo Martins', 'Memória RAM 16GB DDR4'),
(212, 'Bruno Vieira', 'Nobreak Intelbras 1200VA'),
(213, 'Lara Silva', 'Hub USB-C 7 em 1'),
(214, 'Wagner Martins', 'Microfone Condensador Redragon'),
(215, 'Gustavo Fernandes', 'Placa de Vídeo RTX 3060'),
(216, 'Patricia Lopes', 'Suporte para Notebook'),
(217, 'Thiago Carvalho', 'Smartphone Samsung Galaxy'),
(218, 'Bruno Martins', 'Mesa Digitalizadora Wacom'),
(219, 'Felipe Mendes', 'Headset HyperX Cloud II'),
(220, 'João Rodrigues', 'Carregador Indutivo Sem Fio'),
(221, 'Bruno Martins', 'Roteador TP-Link Wi-Fi 6'),
(222, 'Bruno Oliveira', 'Caixa de Som JBL Flip'),
(223, 'Heitor Rodrigues', 'Luminária de Mesa LED'),
(224, 'Mariana Santos', 'Filtro de Linha 6 Tomadas'),
(225, 'Elisa Costa', 'Webcam Logitech C920'),
(226, 'João Costa', 'Mesa Digitalizadora Wacom'),
(227, 'Elisa Lima', 'Memória RAM 16GB DDR4'),
(228, 'Gustavo Lima', 'Microfone Condensador Redragon'),
(229, 'Fernanda Lopes', 'Notebook Dell Inspiron'),
(230, 'Daniela Ribeiro', 'Suporte para Notebook'),
(231, 'Eduardo Rocha', 'Monitor LG 29 Ultrawide'),
(232, 'Bruno Pereira', 'Webcam Logitech C920'),
(233, 'Bruno Barbosa', 'Cadeira Ergonômica Flexform'),
(234, 'Rafael Rodrigues', 'Smartphone Samsung Galaxy'),
(235, 'Helena Vieira', 'Webcam Logitech C920'),
(236, 'João Nascimento', 'Filtro de Linha 6 Tomadas'),
(237, 'Diego Ferreira', 'Carregador Indutivo Sem Fio'),
(238, 'Helena Ferreira', 'HD Externo Toshiba 1TB'),
(239, 'Gabriel Vieira', 'Notebook Dell Inspiron'),
(240, 'Wagner Vieira', 'Gabinete ATX Gamer'),
(241, 'Elisa Martins', 'Fonte Corsair 650W'),
(242, 'Nicolas Oliveira', 'Roteador TP-Link Wi-Fi 6'),
(243, 'Rafael Souza', 'Fonte Corsair 650W'),
(244, 'Wagner Dias', 'Carregador Indutivo Sem Fio'),
(245, 'Helena Vieira', 'Placa Mãe Asus TUF'),
(246, 'Carlos Ribeiro', 'Impressora HP DeskJet'),
(247, 'Heitor Dias', 'Hub USB-C 7 em 1'),
(248, 'Eduardo Soares', 'Caixa de Som JBL Flip'),
(249, 'Beatriz Silva', 'SSD M.2 NVMe 1TB Kingston'),
(250, 'Matheus Souza', 'SSD M.2 NVMe 1TB Kingston'),
(251, 'Diego Rocha', 'Microfone Condensador Redragon'),
(252, 'João Nascimento', 'Cadeira Ergonômica Flexform'),
(253, 'Heitor Ferreira', 'Placa de Vídeo RTX 3060'),
(254, 'Thiago Barbosa', 'Placa Mãe Asus TUF'),
(255, 'Lara Almeida', 'SSD M.2 NVMe 1TB Kingston'),
(256, 'Thiago Costa', 'Suporte para Notebook'),
(257, 'Fernanda Lima', 'Luminária de Mesa LED'),
(258, 'Rafael Almeida', 'Roteador TP-Link Wi-Fi 6'),
(259, 'Elisa Costa', 'Notebook Dell Inspiron'),
(260, 'Matheus Costa', 'Headset HyperX Cloud II'),
(261, 'Matheus Alves', 'Hub USB-C 7 em 1'),
(262, 'Sofia Costa', 'Filtro de Linha 6 Tomadas'),
(263, 'Thiago Fernandes', 'Notebook Dell Inspiron'),
(264, 'Nicolas Oliveira', 'Suporte para Notebook'),
(265, 'Gustavo Lopes', 'Impressora HP DeskJet'),
(266, 'Rafael Nascimento', 'Smartphone Samsung Galaxy'),
(267, 'Matheus Almeida', 'Placa Mãe Asus TUF'),
(268, 'Bruno Oliveira', 'HD Externo Toshiba 1TB'),
(269, 'Patricia Martins', 'Fonte Corsair 650W'),
(270, 'Rafael Gomes', 'Gabinete ATX Gamer'),
(271, 'Diego Lopes', 'Impressora HP DeskJet'),
(272, 'Caio Carvalho', 'Placa de Vídeo RTX 3060'),
(273, 'Beatriz Ribeiro', 'Fonte Corsair 650W'),
(274, 'João Lima', 'HD Externo Toshiba 1TB'),
(275, 'Sofia Pereira', 'Mouse Sem Fio Dell'),
(276, 'Nicolas Costa', 'Mouse Sem Fio Dell'),
(277, 'Mariana Alves', 'Webcam Logitech C920'),
(278, 'Lara Lima', 'Placa de Vídeo RTX 3060'),
(279, 'Vanessa Souza', 'Microfone Condensador Redragon'),
(280, 'Nicolas Gomes', 'Suporte para Notebook'),
(281, 'Diego Ferreira', 'HD Externo Toshiba 1TB'),
(282, 'Ana Nascimento', 'Impressora HP DeskJet'),
(283, 'Igor Lima', 'Monitor LG 29 Ultrawide'),
(284, 'Daniela Fernandes', 'HD Externo Toshiba 1TB'),
(285, 'Igor Rocha', 'Memória RAM 16GB DDR4'),
(286, 'Matheus Souza', 'Notebook Dell Inspiron'),
(287, 'Vanessa Lopes', 'Smartphone Samsung Galaxy'),
(288, 'Isabela Costa', 'Headset HyperX Cloud II'),
(289, 'Daniela Lima', 'Smartphone Samsung Galaxy'),
(290, 'Helena Oliveira', 'Nobreak Intelbras 1200VA'),
(291, 'Matheus Oliveira', 'Roteador TP-Link Wi-Fi 6'),
(292, 'Daniela Rodrigues', 'Cadeira Ergonômica Flexform'),
(293, 'Wagner Oliveira', 'Suporte para Notebook'),
(294, 'Helena Fernandes', 'Memória RAM 16GB DDR4'),
(295, 'Gustavo Barbosa', 'Carregador Indutivo Sem Fio'),
(296, 'Patricia Soares', 'Nobreak Intelbras 1200VA'),
(297, 'Isabela Almeida', 'HD Externo Toshiba 1TB'),
(298, 'Heitor Gomes', 'Roteador TP-Link Wi-Fi 6'),
(299, 'Daniela Barbosa', 'Placa de Vídeo RTX 3060'),
(300, 'Gabriel Alves', 'Caixa de Som JBL Flip'),
(301, 'Oliveira Lima', 'Gabinete ATX Gamer'),
(302, 'Fernanda Ferreira', 'Suporte para Notebook'),
(303, 'Mariana Fernandes', 'Teclado Mecânico Logitech'),
(304, 'Lucas Silva', 'SSD M.2 NVMe 1TB Kingston'),
(305, 'Isabela Nascimento', 'Carregador Indutivo Sem Fio'),
(306, 'Lara Gomes', 'Monitor LG 29 Ultrawide'),
(307, 'Patricia Gomes', 'Fonte Corsair 650W'),
(308, 'Vanessa Nascimento', 'Luminária de Mesa LED'),
(309, 'Eduardo Dias', 'Suporte para Notebook'),
(310, 'Sofia Rocha', 'Roteador TP-Link Wi-Fi 6'),
(311, 'Nicolas Carvalho', 'Mouse Sem Fio Dell'),
(312, 'Patricia Rocha', 'Cadeira Ergonômica Flexform'),
(313, 'Thiago Rodrigues', 'Teclado Mecânico Logitech'),
(314, 'Daniela Ferreira', 'Placa Mãe Asus TUF'),
(315, 'Wagner Barbosa', 'Placa de Vídeo RTX 3060'),
(316, 'Vanessa Almeida', 'Mouse Sem Fio Dell'),
(317, 'João Nascimento', 'HD Externo Toshiba 1TB'),
(318, 'Felipe Lima', 'Tablet Apple iPad'),
(319, 'Matheus Almeida', 'Teclado Mecânico Logitech'),
(320, 'Carlos Carvalho', 'Placa de Vídeo RTX 3060'),
(321, 'Aline Barbosa', 'Filtro de Linha 6 Tomadas'),
(322, 'Bruno Oliveira', 'Suporte para Notebook'),
(323, 'Bruno Dias', 'Microfone Condensador Redragon'),
(324, 'Thiago Vieira', 'Monitor LG 29 Ultrawide'),
(325, 'Mariana Lopes', 'Tablet Apple iPad'),
(326, 'Isabela Lima', 'Headset HyperX Cloud II'),
(327, 'Heitor Rocha', 'Microfone Condensador Redragon'),
(328, 'Matheus Oliveira', 'Smartphone Samsung Galaxy'),
(329, 'Caio Carvalho', 'Mesa Digitalizadora Wacom'),
(330, 'Aline Dias', 'Mouse Sem Fio Dell'),
(331, 'Lucas Costa', 'SSD M.2 NVMe 1TB Kingston'),
(332, 'Matheus Gomes', 'Gabinete ATX Gamer'),
(333, 'Felipe Fernandes', 'Monitor LG 29 Ultrawide'),
(334, 'João Oliveira', 'Mesa Digitalizadora Wacom'),
(335, 'Sofia Costa', 'Mouse Sem Fio Dell'),
(336, 'Felipe Soares', 'Microfone Condensador Redragon'),
(337, 'Ana Dias', 'Impressora HP DeskJet'),
(338, 'João Carvalho', 'Monitor LG 29 Ultrawide'),
(339, 'Nicolas Soares', 'Hub USB-C 7 em 1'),
(340, 'Matheus Rocha', 'Luminária de Mesa LED'),
(341, 'Daniela Alves', 'Filtro de Linha 6 Tomadas'),
(342, 'Igor Gomes', 'Luminária de Mesa LED'),
(343, 'Matheus Souza', 'Notebook Dell Inspiron'),
(344, 'Rafael Nascimento', 'Headset HyperX Cloud II'),
(345, 'Wagner Fernandes', 'Notebook Dell Inspiron'),
(346, 'Gustavo Oliveira', 'Suporte para Notebook'),
(347, 'Helena Almeida', 'Mouse Sem Fio Dell'),
(348, 'Juliana Lopes', 'Fonte Corsair 650W'),
(349, 'Vanessa Soares', 'Fonte Corsair 650W'),
(350, 'Thiago Carvalho', 'Microfone Condensador Redragon'),
(351, 'Lara Lopes', 'Suporte para Notebook'),
(352, 'João Fernandes', 'Cadeira Ergonômica Flexform'),
(353, 'Elisa Alves', 'Carregador Indutivo Sem Fio'),
(354, 'Igor Oliveira', 'Filtro de Linha 6 Tomadas'),
(355, 'Gustavo Costa', 'Placa Mãe Asus TUF'),
(356, 'Thiago Silva', 'HD Externo Toshiba 1TB'),
(357, 'Wagner Vieira', 'Roteador TP-Link Wi-Fi 6'),
(358, 'Matheus Rodrigues', 'Luminária de Mesa LED'),
(359, 'Lara Ribeiro', 'Mesa Digitalizadora Wacom'),
(360, 'Elisa Almeida', 'Mesa Digitalizadora Wacom'),
(361, 'Nicolas Nascimento', 'Suporte para Notebook'),
(362, 'Elisa Pereira', 'Memória RAM 16GB DDR4'),
(363, 'Gustavo Santos', 'Mesa Digitalizadora Wacom'),
(364, 'Lara Nascimento', 'Placa Mãe Asus TUF'),
(365, 'Elisa Martins', 'Gabinete ATX Gamer'),
(366, 'Juliana Lopes', 'Monitor LG 29 Ultrawide'),
(367, 'Igor Soares', 'Roteador TP-Link Wi-Fi 6'),
(368, 'Beatriz Souza', 'Luminária de Mesa LED'),
(369, 'Gabriel Soares', 'Luminária de Mesa LED'),
(370, 'Ana Mendes', 'Cadeira Ergonômica Flexform'),
(371, 'Gustavo Rocha', 'Cadeira Ergonômica Flexform'),
(372, 'Eduardo Lopes', 'Placa Mãe Asus TUF'),
(373, 'Sofia Costa', 'Carregador Indutivo Sem Fio'),
(374, 'Felipe Rocha', 'Teclado Mecânico Logitech'),
(375, 'Beatriz Dias', 'Impressora HP DeskJet'),
(376, 'Elisa Costa', 'Caixa de Som JBL Flip'),
(377, 'Matheus Fernandes', 'Monitor LG 29 Ultrawide'),
(378, 'Eduardo Pereira', 'Caixa de Som JBL Flip'),
(379, 'Vanessa Pereira', 'Placa de Vídeo RTX 3060'),
(380, 'Fernanda Carvalho', 'Mouse Sem Fio Dell'),
(381, 'Gabriel Almeida', 'Headset HyperX Cloud II'),
(382, 'Wagner Silva', 'Monitor LG 29 Ultrawide'),
(383, 'Aline Santos', 'HD Externo Toshiba 1TB'),
(384, 'Caio Ribeiro', 'SSD M.2 NVMe 1TB Kingston'),
(385, 'Juliana Pereira', 'Tablet Apple iPad'),
(386, 'Gustavo Vieira', 'Gabinete ATX Gamer'),
(387, 'Mariana Ferreira', 'Headset HyperX Cloud II'),
(388, 'Fernanda Barbosa', 'Nobreak Intelbras 1200VA'),
(389, 'Rafael Lopes', 'Roteador TP-Link Wi-Fi 6'),
(390, 'Juliana Pereira', 'Luminária de Mesa LED'),
(391, 'Sofia Almeida', 'Filtro de Linha 6 Tomadas'),
(392, 'Ana Almeida', 'HD Externo Toshiba 1TB'),
(393, 'Lucas Oliveira', 'Luminária de Mesa LED'),
(394, 'Caio Vieira', 'HD Externo Toshiba 1TB'),
(395, 'Heitor Nascimento', 'Filtro de Linha 6 Tomadas'),
(396, 'João Gomes', 'Webcam Logitech C920'),
(397, 'Elisa Lopes', 'Mouse Sem Fio Dell'),
(398, 'Rafael Martins', 'Roteador TP-Link Wi-Fi 6'),
(399, 'Caio Vieira', 'HD Externo Toshiba 1TB'),
(400, 'Vanessa Silva', 'Microfone Condensador Redragon'),
(401, 'Felipe Lima', 'Notebook Dell Inspiron'),
(402, 'Daniela Barbosa', 'Placa de Vídeo RTX 3060'),
(403, 'Matheus Gomes', 'Memória RAM 16GB DDR4'),
(404, 'Patricia Barbosa', 'Placa Mãe Asus TUF'),
(405, 'Caio Pereira', 'Caixa de Som JBL Flip'),
(406, 'Nicolas Barbosa', 'Filtro de Linha 6 Tomadas'),
(407, 'Igor Rocha', 'Mouse Sem Fio Dell'),
(408, 'Carlos Gomes', 'Placa Mãe Asus TUF'),
(409, 'Isabela Santos', 'Roteador TP-Link Wi-Fi 6'),
(410, 'Diego Mendes', 'Cadeira Ergonômica Flexform'),
(411, 'Fernanda Gomes', 'Mesa Digitalizadora Wacom'),
(412, 'Gustavo Ferreira', 'Webcam Logitech C920'),
(413, 'Igor Fernandes', 'Hub USB-C 7 em 1'),
(414, 'Thiago Ferreira', 'Filtro de Linha 6 Tomadas'),
(415, 'Lara Gomes', 'Placa de Vídeo RTX 3060'),
(416, 'Beatriz Souza', 'Luminária de Mesa LED'),
(417, 'Eduardo Rodrigues', 'Memória RAM 16GB DDR4'),
(418, 'Patricia Dias', 'Placa de Vídeo RTX 3060'),
(419, 'Felipe Fernandes', 'Hub USB-C 7 em 1'),
(420, 'Fernanda Martins', 'Notebook Dell Inspiron'),
(421, 'Sofia Fernandes', 'Mouse Sem Fio Dell'),
(422, 'João Ribeiro', 'Gabinete ATX Gamer'),
(423, 'Sofia Vieira', 'Nobreak Intelbras 1200VA'),
(424, 'Diego Souza', 'Gabinete ATX Gamer'),
(425, 'Patricia Lopes', 'Notebook Dell Inspiron'),
(426, 'Aline Barbosa', 'Suporte para Notebook'),
(427, 'Eduardo Rocha', 'Microfone Condensador Redragon'),
(428, 'João Nascimento', 'HD Externo Toshiba 1TB'),
(429, 'Gustavo Souza', 'Cadeira Ergonômica Flexform'),
(430, 'Carlos Santos', 'HD Externo Toshiba 1TB'),
(431, 'Matheus Souza', 'Mouse Sem Fio Dell'),
(432, 'Rafael Fernandes', 'Cadeira Ergonômica Flexform'),
(433, 'Elisa Almeida', 'Hub USB-C 7 em 1'),
(434, 'Gustavo Vieira', 'Placa de Vídeo RTX 3060'),
(435, 'Juliana Carvalho', 'Caixa de Som JBL Flip'),
(436, 'Gabriel Lopes', 'Carregador Indutivo Sem Fio'),
(437, 'Gustavo Lima', 'Monitor LG 29 Ultrawide'),
(438, 'Diego Alves', 'Luminária de Mesa LED'),
(439, 'Isabela Pereira', 'Hub USB-C 7 em 1'),
(440, 'Gabriel Dias', 'Hub USB-C 7 em 1'),
(441, 'Caio Santos', 'Nobreak Intelbras 1200VA'),
(442, 'Thiago Alves', 'Mouse Sem Fio Dell'),
(443, 'João Oliveira', 'Gabinete ATX Gamer'),
(444, 'Oliveira Rocha', 'Caixa de Som JBL Flip'),
(445, 'Bruno Santos', 'Placa Mãe Asus TUF'),
(446, 'Beatriz Pereira', 'Cadeira Ergonômica Flexform'),
(447, 'Oliveira Oliveira', 'Microfone Condensador Redragon'),
(448, 'Oliveira Vieira', 'Webcam Logitech C920'),
(449, 'Patricia Costa', 'Memória RAM 16GB DDR4'),
(450, 'Juliana Barbosa', 'Notebook Dell Inspiron'),
(451, 'Thiago Rodrigues', 'Cadeira Ergonômica Flexform'),
(452, 'Sofia Ferreira', 'Mouse Sem Fio Dell'),
(453, 'Bruno Rodrigues', 'Notebook Dell Inspiron'),
(454, 'Caio Pereira', 'Roteador TP-Link Wi-Fi 6'),
(455, 'Aline Silva', 'Headset HyperX Cloud II'),
(456, 'Sofia Santos', 'Cadeira Ergonômica Flexform'),
(457, 'Gustavo Soares', 'Mouse Sem Fio Dell'),
(458, 'Eduardo Lopes', 'Luminária de Mesa LED'),
(459, 'Diego Soares', 'Roteador TP-Link Wi-Fi 6'),
(460, 'Gabriel Almeida', 'Tablet Apple iPad'),
(461, 'Patricia Barbosa', 'Monitor LG 29 Ultrawide'),
(462, 'Wagner Almeida', 'Caixa de Som JBL Flip'),
(463, 'Bruno Santos', 'Smartphone Samsung Galaxy'),
(464, 'Felipe Carvalho', 'Gabinete ATX Gamer'),
(465, 'Gabriel Lopes', 'Fonte Corsair 650W'),
(466, 'Isabela Oliveira', 'Teclado Mecânico Logitech'),
(467, 'Aline Barbosa', 'Cadeira Ergonômica Flexform'),
(468, 'Eduardo Rodrigues', 'Filtro de Linha 6 Tomadas'),
(469, 'Aline Martins', 'Carregador Indutivo Sem Fio'),
(470, 'Vanessa Almeida', 'Tablet Apple iPad'),
(471, 'Heitor Souza', 'Placa Mãe Asus TUF'),
(472, 'Helena Rocha', 'Caixa de Som JBL Flip'),
(473, 'Oliveira Carvalho', 'Luminária de Mesa LED'),
(474, 'Patricia Carvalho', 'Mesa Digitalizadora Wacom'),
(475, 'João Martins', 'SSD M.2 NVMe 1TB Kingston'),
(476, 'Gabriel Costa', 'SSD M.2 NVMe 1TB Kingston'),
(477, 'Aline Dias', 'Filtro de Linha 6 Tomadas'),
(478, 'Diego Rodrigues', 'Gabinete ATX Gamer'),
(479, 'Lara Oliveira', 'Teclado Mecânico Logitech'),
(480, 'Fernanda Oliveira', 'SSD M.2 NVMe 1TB Kingston'),
(481, 'Gabriel Mendes', 'Placa de Vídeo RTX 3060'),
(482, 'Diego Rodrigues', 'Impressora HP DeskJet'),
(483, 'Daniela Vieira', 'Impressora HP DeskJet'),
(484, 'Beatriz Dias', 'Mouse Sem Fio Dell'),
(485, 'Gustavo Ribeiro', 'Gabinete ATX Gamer'),
(486, 'Heitor Mendes', 'Monitor LG 29 Ultrawide'),
(487, 'Vanessa Barbosa', 'HD Externo Toshiba 1TB'),
(488, 'Caio Souza', 'Roteador TP-Link Wi-Fi 6'),
(489, 'Oliveira Rodrigues', 'Gabinete ATX Gamer'),
(490, 'Lara Pereira', 'Mouse Sem Fio Dell'),
(491, 'Caio Fernandes', 'Hub USB-C 7 em 1'),
(492, 'Helena Lima', 'Roteador TP-Link Wi-Fi 6'),
(493, 'Patricia Carvalho', 'Impressora HP DeskJet'),
(494, 'Bruno Barbosa', 'Gabinete ATX Gamer'),
(495, 'Thiago Silva', 'Headset HyperX Cloud II'),
(496, 'Thiago Nascimento', 'Memória RAM 16GB DDR4'),
(497, 'Wagner Costa', 'Hub USB-C 7 em 1'),
(498, 'Ana Ferreira', 'Cadeira Ergonômica Flexform'),
(499, 'Felipe Oliveira', 'Cadeira Ergonômica Flexform'),
(500, 'Bruno Oliveira', 'Placa de Vídeo RTX 3060'),
(501, 'Oliveira Martins', 'SSD M.2 NVMe 1TB Kingston'),
(502, 'João Costa', 'Headset HyperX Cloud II'),
(503, 'Diego Gomes', 'Placa de Vídeo RTX 3060'),
(504, 'Aline Vieira', 'Carregador Indutivo Sem Fio'),
(505, 'Fernanda Santos', 'Cadeira Ergonômica Flexform'),
(506, 'Lucas Barbosa', 'Monitor LG 29 Ultrawide'),
(507, 'Fernanda Lima', 'Luminária de Mesa LED'),
(508, 'Heitor Lopes', 'Carregador Indutivo Sem Fio'),
(509, 'Isabela Carvalho', 'Filtro de Linha 6 Tomadas'),
(510, 'Oliveira Soares', 'Mouse Sem Fio Dell'),
(511, 'Caio Carvalho', 'Mouse Sem Fio Dell'),
(512, 'Vanessa Dias', 'Gabinete ATX Gamer'),
(513, 'Matheus Soares', 'Gabinete ATX Gamer'),
(514, 'Wagner Santos', 'Suporte para Notebook'),
(515, 'Felipe Barbosa', 'Monitor LG 29 Ultrawide'),
(516, 'Ana Alves', 'HD Externo Toshiba 1TB'),
(517, 'Oliveira Rodrigues', 'Memória RAM 16GB DDR4'),
(518, 'Sofia Gomes', 'Mesa Digitalizadora Wacom'),
(519, 'Helena Silva', 'Smartphone Samsung Galaxy'),
(520, 'Heitor Ferreira', 'Cadeira Ergonômica Flexform'),
(521, 'Elisa Fernandes', 'Fonte Corsair 650W'),
(522, 'Patricia Soares', 'Impressora HP DeskJet'),
(523, 'Caio Oliveira', 'Nobreak Intelbras 1200VA'),
(524, 'Carlos Carvalho', 'Notebook Dell Inspiron'),
(525, 'João Oliveira', 'Mesa Digitalizadora Wacom'),
(526, 'Heitor Vieira', 'Nobreak Intelbras 1200VA'),
(527, 'Gustavo Gomes', 'Mouse Sem Fio Dell'),
(528, 'Felipe Silva', 'Mesa Digitalizadora Wacom'),
(529, 'Lucas Barbosa', 'Luminária de Mesa LED'),
(530, 'Diego Oliveira', 'SSD M.2 NVMe 1TB Kingston'),
(531, 'Gabriel Pereira', 'SSD M.2 NVMe 1TB Kingston'),
(532, 'Felipe Soares', 'Teclado Mecânico Logitech'),
(533, 'Felipe Gomes', 'Placa de Vídeo RTX 3060'),
(534, 'Beatriz Pereira', 'Mesa Digitalizadora Wacom'),
(535, 'Lucas Oliveira', 'Tablet Apple iPad'),
(536, 'Helena Soares', 'Tablet Apple iPad'),
(537, 'Nicolas Ribeiro', 'Hub USB-C 7 em 1'),
(538, 'Juliana Pereira', 'Mouse Sem Fio Dell'),
(539, 'Juliana Lima', 'Webcam Logitech C920'),
(540, 'Mariana Barbosa', 'Cadeira Ergonômica Flexform'),
(541, 'Eduardo Ferreira', 'Memória RAM 16GB DDR4'),
(542, 'Matheus Almeida', 'Memória RAM 16GB DDR4'),
(543, 'Isabela Dias', 'Roteador TP-Link Wi-Fi 6'),
(544, 'Aline Rocha', 'Mesa Digitalizadora Wacom'),
(545, 'Juliana Almeida', 'Teclado Mecânico Logitech'),
(546, 'Lara Almeida', 'Caixa de Som JBL Flip'),
(547, 'Wagner Lima', 'Roteador TP-Link Wi-Fi 6'),
(548, 'Daniela Ribeiro', 'Tablet Apple iPad'),
(549, 'Eduardo Gomes', 'Luminária de Mesa LED'),
(550, 'Isabela Santos', 'Monitor LG 29 Ultrawide'),
(551, 'Diego Gomes', 'Teclado Mecânico Logitech'),
(552, 'Fernanda Barbosa', 'Carregador Indutivo Sem Fio'),
(553, 'Elisa Almeida', 'Roteador TP-Link Wi-Fi 6'),
(554, 'Carlos Almeida', 'Placa Mãe Asus TUF'),
(555, 'Nicolas Costa', 'Carregador Indutivo Sem Fio'),
(556, 'Lara Soares', 'Cadeira Ergonômica Flexform'),
(557, 'Daniela Almeida', 'Mouse Sem Fio Dell'),
(558, 'Beatriz Nascimento', 'Teclado Mecânico Logitech'),
(559, 'Mariana Santos', 'Suporte para Notebook'),
(560, 'Isabela Almeida', 'Tablet Apple iPad'),
(561, 'Lucas Ribeiro', 'Hub USB-C 7 em 1'),
(562, 'Vanessa Martins', 'SSD M.2 NVMe 1TB Kingston'),
(563, 'Christian Taylor', 'Protoboard'),
(564, 'Daniela Rocha', 'Caixa de Som JBL Flip'),
(565, 'Beatriz Oliveira', 'Mesa Digitalizadora Wacom'),
(566, 'Gabriel Fernandes', 'Gabinete ATX Gamer'),
(567, 'Elisa Gomes', 'Filtro de Linha 6 Tomadas'),
(568, 'Juliana Costa', 'Teclado Mecânico Logitech'),
(569, 'Juliana Ribeiro', 'HD Externo Toshiba 1TB'),
(570, 'Felipe Rodrigues', 'Carregador Indutivo Sem Fio'),
(571, 'Fernanda Gomes', 'Impressora HP DeskJet'),
(572, 'Elisa Rocha', 'Placa Mãe Asus TUF'),
(573, 'Beatriz Rodrigues', 'Gabinete ATX Gamer'),
(574, 'Fernanda Rocha', 'Gabinete ATX Gamer'),
(575, 'Heitor Soares', 'Hub USB-C 7 em 1'),
(576, 'Bruno Ribeiro', 'HD Externo Toshiba 1TB'),
(577, 'Mariana Alves', 'Mesa Digitalizadora Wacom'),
(578, 'Matheus Alves', 'Suporte para Notebook'),
(579, 'Igor Rodrigues', 'Teclado Mecânico Logitech'),
(580, 'Vanessa Souza', 'Tablet Apple iPad'),
(581, 'Carlos Dias', 'Mesa Digitalizadora Wacom'),
(582, 'Igor Barbosa', 'Nobreak Intelbras 1200VA'),
(583, 'Juliana Ferreira', 'Headset HyperX Cloud II'),
(584, 'Lucas Mendes', 'Luminária de Mesa LED'),
(585, 'Carlos Carvalho', 'Hub USB-C 7 em 1'),
(586, 'Rafael Almeida', 'Carregador Indutivo Sem Fio'),
(587, 'Vanessa Mendes', 'Placa Mãe Asus TUF'),
(588, 'Isabela Pereira', 'Impressora HP DeskJet'),
(589, 'Rafael Gomes', 'Placa Mãe Asus TUF'),
(590, 'Lara Alves', 'Hub USB-C 7 em 1'),
(591, 'Isabela Almeida', 'Memória RAM 16GB DDR4'),
(592, 'Vanessa Martins', 'Tablet Apple iPad'),
(593, 'Gustavo Ferreira', 'Microfone Condensador Redragon'),
(594, 'Nicolas Barbosa', 'Cadeira Ergonômica Flexform'),
(595, 'Sofia Santos', 'Caixa de Som JBL Flip'),
(596, 'Lara Ribeiro', 'Impressora HP DeskJet'),
(597, 'Gabriel Nascimento', 'Tablet Apple iPad'),
(598, 'Helena Gomes', 'Teclado Mecânico Logitech'),
(599, 'Lucas Lima', 'Luminária de Mesa LED'),
(600, 'Juliana Carvalho', 'Teclado Mecânico Logitech'),
(601, 'Patricia Almeida', 'Hub USB-C 7 em 1'),
(602, 'Bruno Carvalho', 'Monitor LG 29 Ultrawide'),
(603, 'Felipe Soares', 'Hub USB-C 7 em 1'),
(604, 'Rafael Martins', 'Teclado Mecânico Logitech'),
(605, 'Diego Pereira', 'Notebook Dell Inspiron'),
(606, 'Aline Souza', 'Microfone Condensador Redragon'),
(607, 'Beatriz Rodrigues', 'Cadeira Ergonômica Flexform'),
(608, 'Carlos Gomes', 'Microfone Condensador Redragon'),
(609, 'Lara Nascimento', 'Microfone Condensador Redragon'),
(610, 'Igor Nascimento', 'Smartphone Samsung Galaxy'),
(611, 'Isabela Barbosa', 'Notebook Dell Inspiron'),
(612, 'Fernanda Silva', 'Filtro de Linha 6 Tomadas'),
(613, 'Oliveira Rodrigues', 'Impressora HP DeskJet'),
(614, 'Heitor Souza', 'Memória RAM 16GB DDR4'),
(615, 'Vanessa Pereira', 'HD Externo Toshiba 1TB'),
(616, 'Helena Santos', 'Suporte para Notebook'),
(617, 'Gustavo Rocha', 'Placa Mãe Asus TUF'),
(618, 'João Oliveira', 'Mouse Sem Fio Dell'),
(619, 'Matheus Barbosa', 'Impressora HP DeskJet'),
(620, 'Bruno Rocha', 'Tablet Apple iPad'),
(621, 'Rafael Nascimento', 'Cadeira Ergonômica Flexform'),
(622, 'Vanessa Carvalho', 'Notebook Dell Inspiron'),
(623, 'Caio Pereira', 'Roteador TP-Link Wi-Fi 6'),
(624, 'Gustavo Ferreira', 'Gabinete ATX Gamer'),
(625, 'Fernanda Soares', 'Hub USB-C 7 em 1'),
(626, 'Eduardo Soares', 'Impressora HP DeskJet'),
(627, 'Bruno Martins', 'Smartphone Samsung Galaxy'),
(628, 'Carlos Rocha', 'Nobreak Intelbras 1200VA'),
(629, 'Diego Lima', 'Placa de Vídeo RTX 3060'),
(630, 'Bruno Ribeiro', 'Placa Mãe Asus TUF'),
(631, 'Eduardo Ribeiro', 'Suporte para Notebook'),
(632, 'Gabriel Vieira', 'Placa de Vídeo RTX 3060'),
(633, 'Beatriz Rodrigues', 'Monitor LG 29 Ultrawide'),
(634, 'Caio Fernandes', 'Mesa Digitalizadora Wacom'),
(635, 'Mariana Dias', 'Luminária de Mesa LED'),
(636, 'Lara Rocha', 'Headset HyperX Cloud II'),
(637, 'Igor Oliveira', 'Fonte Corsair 650W'),
(638, 'João Santos', 'HD Externo Toshiba 1TB'),
(639, 'Nicolas Santos', 'Placa Mãe Asus TUF'),
(640, 'Nicolas Santos', 'Mesa Digitalizadora Wacom'),
(641, 'Wagner Soares', 'Nobreak Intelbras 1200VA'),
(642, 'Lara Lima', 'Monitor LG 29 Ultrawide'),
(643, 'Nicolas Gomes', 'Hub USB-C 7 em 1'),
(644, 'Daniela Rocha', 'Mesa Digitalizadora Wacom'),
(645, 'Thiago Souza', 'Placa Mãe Asus TUF'),
(646, 'Diego Carvalho', 'Nobreak Intelbras 1200VA'),
(647, 'Isabela Martins', 'Mesa Digitalizadora Wacom'),
(648, 'Mariana Lopes', 'Fonte Corsair 650W'),
(649, 'Matheus Ribeiro', 'Placa Mãe Asus TUF'),
(650, 'Thiago Oliveira', 'Placa de Vídeo RTX 3060'),
(651, 'Heitor Oliveira', 'SSD M.2 NVMe 1TB Kingston'),
(652, 'Mariana Fernandes', 'HD Externo Toshiba 1TB'),
(653, 'Aline Souza', 'Teclado Mecânico Logitech'),
(654, 'Aline Dias', 'HD Externo Toshiba 1TB'),
(655, 'Wagner Almeida', 'Carregador Indutivo Sem Fio'),
(656, 'Heitor Ferreira', 'Fonte Corsair 650W'),
(657, 'Isabela Ribeiro', 'Luminária de Mesa LED'),
(658, 'Carlos Mendes', 'Hub USB-C 7 em 1'),
(659, 'Heitor Lima', 'Caixa de Som JBL Flip'),
(660, 'Daniela Oliveira', 'Gabinete ATX Gamer'),
(661, 'Felipe Ribeiro', 'Tablet Apple iPad'),
(662, 'Lucas Silva', 'Cadeira Ergonômica Flexform'),
(663, 'Isabela Santos', 'Cadeira Ergonômica Flexform'),
(664, 'Eduardo Pereira', 'Memória RAM 16GB DDR4'),
(665, 'Diego Ribeiro', 'Nobreak Intelbras 1200VA'),
(666, 'Carlos Barbosa', 'Cadeira Ergonômica Flexform'),
(667, 'Isabela Ribeiro', 'Hub USB-C 7 em 1'),
(668, 'Isabela Oliveira', 'Roteador TP-Link Wi-Fi 6'),
(669, 'Igor Soares', 'Hub USB-C 7 em 1'),
(670, 'Felipe Costa', 'Caixa de Som JBL Flip'),
(671, 'Thiago Pereira', 'Mouse Sem Fio Dell'),
(672, 'Bruno Mendes', 'Headset HyperX Cloud II'),
(673, 'Matheus Soares', 'Nobreak Intelbras 1200VA'),
(674, 'Helena Lima', 'Memória RAM 16GB DDR4'),
(675, 'Sofia Nascimento', 'Luminária de Mesa LED'),
(676, 'Oliveira Barbosa', 'HD Externo Toshiba 1TB'),
(677, 'Matheus Alves', 'Mouse Sem Fio Dell'),
(678, 'Igor Oliveira', 'Luminária de Mesa LED'),
(679, 'Mariana Nascimento', 'Luminária de Mesa LED'),
(680, 'Fernanda Dias', 'Mesa Digitalizadora Wacom'),
(681, 'Caio Nascimento', 'Teclado Mecânico Logitech'),
(682, 'Vanessa Gomes', 'Headset HyperX Cloud II'),
(683, 'Mariana Ribeiro', 'Tablet Apple iPad'),
(684, 'Patricia Souza', 'Webcam Logitech C920'),
(685, 'Igor Pereira', 'Placa Mãe Asus TUF'),
(686, 'Matheus Silva', 'Hub USB-C 7 em 1'),
(687, 'Diego Almeida', 'Placa Mãe Asus TUF'),
(688, 'Igor Barbosa', 'Teclado Mecânico Logitech'),
(689, 'Eduardo Gomes', 'Nobreak Intelbras 1200VA'),
(690, 'Lara Soares', 'SSD M.2 NVMe 1TB Kingston'),
(691, 'Gustavo Vieira', 'Teclado Mecânico Logitech'),
(692, 'Igor Costa', 'Caixa de Som JBL Flip'),
(693, 'Eduardo Almeida', 'Luminária de Mesa LED'),
(694, 'Caio Rodrigues', 'Microfone Condensador Redragon'),
(695, 'Mariana Rodrigues', 'SSD M.2 NVMe 1TB Kingston'),
(696, 'Daniela Souza', 'Tablet Apple iPad'),
(697, 'Juliana Gomes', 'Headset HyperX Cloud II'),
(698, 'Lucas Costa', 'Fonte Corsair 650W'),
(699, 'Patricia Ribeiro', 'Tablet Apple iPad'),
(700, 'Vanessa Oliveira', 'Filtro de Linha 6 Tomadas'),
(701, 'Nicolas Rocha', 'Impressora HP DeskJet'),
(702, 'Thiago Rodrigues', 'Caixa de Som JBL Flip'),
(703, 'Wagner Barbosa', 'Impressora HP DeskJet'),
(704, 'Fernanda Soares', 'Caixa de Som JBL Flip'),
(705, 'Lucas Vieira', 'Roteador TP-Link Wi-Fi 6'),
(706, 'Juliana Ferreira', 'Gabinete ATX Gamer'),
(707, 'Beatriz Vieira', 'Monitor LG 29 Ultrawide'),
(708, 'Bruno Oliveira', 'Monitor LG 29 Ultrawide'),
(709, 'Sofia Rocha', 'Webcam Logitech C920'),
(710, 'Gustavo Barbosa', 'Caixa de Som JBL Flip'),
(711, 'Bruno Lopes', 'Caixa de Som JBL Flip'),
(712, 'Vanessa Rocha', 'HD Externo Toshiba 1TB'),
(713, 'Lara Pereira', 'Placa Mãe Asus TUF'),
(714, 'Felipe Gomes', 'Luminária de Mesa LED'),
(715, 'Eduardo Nascimento', 'Monitor LG 29 Ultrawide'),
(716, 'Lucas Almeida', 'SSD M.2 NVMe 1TB Kingston'),
(717, 'Lara Almeida', 'Webcam Logitech C920'),
(718, 'Beatriz Barbosa', 'Cadeira Ergonômica Flexform'),
(719, 'Aline Nascimento', 'Mesa Digitalizadora Wacom'),
(720, 'Caio Martins', 'Cadeira Ergonômica Flexform'),
(721, 'Diego Soares', 'Impressora HP DeskJet'),
(722, 'Gabriel Costa', 'Suporte para Notebook'),
(723, 'João Souza', 'Filtro de Linha 6 Tomadas'),
(724, 'Isabela Pereira', 'Cadeira Ergonômica Flexform'),
(725, 'Gabriel Santos', 'HD Externo Toshiba 1TB'),
(726, 'Elisa Barbosa', 'SSD M.2 NVMe 1TB Kingston'),
(727, 'Rafael Ferreira', 'Microfone Condensador Redragon'),
(728, 'Aline Vieira', 'Placa de Vídeo RTX 3060'),
(729, 'Aline Alves', 'Memória RAM 16GB DDR4'),
(730, 'Lucas Lopes', 'Tablet Apple iPad'),
(731, 'João Lopes', 'HD Externo Toshiba 1TB'),
(732, 'Matheus Silva', 'Teclado Mecânico Logitech'),
(733, 'Felipe Soares', 'Luminária de Mesa LED'),
(734, 'Rafael Alves', 'Roteador TP-Link Wi-Fi 6'),
(735, 'Caio Santos', 'Monitor LG 29 Ultrawide'),
(736, 'Vanessa Lopes', 'Carregador Indutivo Sem Fio'),
(737, 'Lara Gomes', 'Impressora HP DeskJet'),
(738, 'Ana Souza', 'SSD M.2 NVMe 1TB Kingston'),
(739, 'Igor Lima', 'Placa de Vídeo RTX 3060'),
(740, 'Diego Martins', 'Hub USB-C 7 em 1'),
(741, 'Carlos Martins', 'Monitor LG 29 Ultrawide'),
(742, 'Nicolas Ribeiro', 'Impressora HP DeskJet'),
(743, 'Vanessa Oliveira', 'Nobreak Intelbras 1200VA'),
(744, 'Isabela Fernandes', 'Filtro de Linha 6 Tomadas'),
(745, 'Helena Rodrigues', 'Mouse Sem Fio Dell'),
(746, 'Felipe Ribeiro', 'Placa Mãe Asus TUF'),
(747, 'Beatriz Fernandes', 'Hub USB-C 7 em 1'),
(748, 'Juliana Alves', 'Carregador Indutivo Sem Fio'),
(749, 'Felipe Soares', 'Monitor LG 29 Ultrawide'),
(750, 'Carlos Santos', 'Cadeira Ergonômica Flexform'),
(751, 'Beatriz Lopes', 'Tablet Apple iPad'),
(752, 'João Rodrigues', 'Carregador Indutivo Sem Fio'),
(753, 'Igor Costa', 'Carregador Indutivo Sem Fio'),
(754, 'Aline Ferreira', 'Nobreak Intelbras 1200VA'),
(755, 'Wagner Vieira', 'Mesa Digitalizadora Wacom'),
(756, 'Matheus Nascimento', 'Roteador TP-Link Wi-Fi 6'),
(757, 'Wagner Lopes', 'Microfone Condensador Redragon'),
(758, 'Bruno Ribeiro', 'Mesa Digitalizadora Wacom'),
(759, 'Helena Carvalho', 'Roteador TP-Link Wi-Fi 6'),
(760, 'Wagner Mendes', 'Fonte Corsair 650W'),
(761, 'Bruno Barbosa', 'Smartphone Samsung Galaxy'),
(762, 'Sofia Rocha', 'Placa Mãe Asus TUF'),
(763, 'Patricia Mendes', 'Monitor LG 29 Ultrawide'),
(764, 'Lara Ferreira', 'Tablet Apple iPad'),
(765, 'Elisa Rodrigues', 'Microfone Condensador Redragon'),
(766, 'Rafael Santos', 'Roteador TP-Link Wi-Fi 6'),
(767, 'Helena Alves', 'Notebook Dell Inspiron'),
(768, 'Isabela Costa', 'SSD M.2 NVMe 1TB Kingston'),
(769, 'Juliana Carvalho', 'Fonte Corsair 650W'),
(770, 'Oliveira Carvalho', 'Tablet Apple iPad'),
(771, 'Lara Mendes', 'Placa de Vídeo RTX 3060'),
(772, 'Daniela Nascimento', 'Cadeira Ergonômica Flexform'),
(773, 'Oliveira Fernandes', 'Mesa Digitalizadora Wacom'),
(774, 'Lara Soares', 'Nobreak Intelbras 1200VA'),
(775, 'Aline Ferreira', 'Luminária de Mesa LED'),
(776, 'Beatriz Fernandes', 'Hub USB-C 7 em 1'),
(777, 'Sofia Barbosa', 'Smartphone Samsung Galaxy'),
(778, 'Nicolas Pereira', 'Filtro de Linha 6 Tomadas'),
(779, 'Wagner Pereira', 'HD Externo Toshiba 1TB'),
(780, 'Vanessa Nascimento', 'Webcam Logitech C920'),
(781, 'Matheus Costa', 'Smartphone Samsung Galaxy'),
(782, 'Caio Fernandes', 'Placa Mãe Asus TUF'),
(783, 'Thiago Gomes', 'Mouse Sem Fio Dell'),
(784, 'Elisa Martins', 'Microfone Condensador Redragon'),
(785, 'Caio Rodrigues', 'HD Externo Toshiba 1TB'),
(786, 'Carlos Gomes', 'Fonte Corsair 650W'),
(787, 'Fernanda Ribeiro', 'Luminária de Mesa LED'),
(788, 'Sofia Mendes', 'Smartphone Samsung Galaxy'),
(789, 'Oliveira Alves', 'Microfone Condensador Redragon'),
(790, 'Thiago Fernandes', 'Fonte Corsair 650W'),
(791, 'Thiago Rodrigues', 'Mouse Sem Fio Dell'),
(792, 'Rafael Pereira', 'Monitor LG 29 Ultrawide'),
(793, 'Patricia Rocha', 'Suporte para Notebook'),
(794, 'Daniela Souza', 'SSD M.2 NVMe 1TB Kingston'),
(795, 'Beatriz Nascimento', 'Smartphone Samsung Galaxy'),
(796, 'Gabriel Dias', 'Memória RAM 16GB DDR4'),
(797, 'Igor Silva', 'Impressora HP DeskJet'),
(798, 'Lucas Carvalho', 'Caixa de Som JBL Flip'),
(799, 'Lara Lopes', 'Caixa de Som JBL Flip'),
(800, 'Nicolas Gomes', 'Mesa Digitalizadora Wacom'),
(801, 'Vanessa Rocha', 'Monitor LG 29 Ultrawide'),
(802, 'Fernanda Rocha', 'Roteador TP-Link Wi-Fi 6'),
(803, 'Patricia Fernandes', 'Placa de Vídeo RTX 3060'),
(804, 'Carlos Ferreira', 'SSD M.2 NVMe 1TB Kingston'),
(805, 'Mariana Santos', 'Microfone Condensador Redragon'),
(806, 'Felipe Lopes', 'Headset HyperX Cloud II'),
(807, 'Vanessa Santos', 'Notebook Dell Inspiron'),
(808, 'Wagner Vieira', 'Carregador Indutivo Sem Fio'),
(809, 'Gabriel Costa', 'HD Externo Toshiba 1TB'),
(810, 'João Rocha', 'Impressora HP DeskJet'),
(811, 'Matheus Rodrigues', 'Tablet Apple iPad'),
(812, 'João Lima', 'Webcam Logitech C920'),
(813, 'Helena Costa', 'Headset HyperX Cloud II'),
(814, 'João Rocha', 'Filtro de Linha 6 Tomadas'),
(815, 'Mariana Silva', 'Placa de Vídeo RTX 3060'),
(816, 'Beatriz Gomes', 'Roteador TP-Link Wi-Fi 6'),
(817, 'Nicolas Ferreira', 'Carregador Indutivo Sem Fio'),
(818, 'Felipe Carvalho', 'Tablet Apple iPad'),
(819, 'Aline Oliveira', 'Nobreak Intelbras 1200VA'),
(820, 'Gabriel Ferreira', 'Cadeira Ergonômica Flexform'),
(821, 'Lara Costa', 'Suporte para Notebook'),
(822, 'Ana Lima', 'Nobreak Intelbras 1200VA'),
(823, 'Rafael Almeida', 'Memória RAM 16GB DDR4'),
(824, 'Thiago Costa', 'HD Externo Toshiba 1TB'),
(825, 'Ana Lima', 'Caixa de Som JBL Flip'),
(826, 'Diego Nascimento', 'Suporte para Notebook'),
(827, 'Daniela Dias', 'Mouse Sem Fio Dell'),
(828, 'João Gomes', 'Headset HyperX Cloud II'),
(829, 'Felipe Dias', 'Tablet Apple iPad'),
(830, 'Wagner Nascimento', 'Mouse Sem Fio Dell'),
(831, 'Vanessa Ribeiro', 'Carregador Indutivo Sem Fio'),
(832, 'Patricia Pereira', 'Cadeira Ergonômica Flexform'),
(833, 'Lara Rodrigues', 'Luminária de Mesa LED'),
(834, 'Diego Carvalho', 'Fonte Corsair 650W'),
(835, 'Lara Fernandes', 'Placa Mãe Asus TUF'),
(836, 'Oliveira Pereira', 'Gabinete ATX Gamer'),
(837, 'Fernanda Soares', 'Luminária de Mesa LED'),
(838, 'Diego Oliveira', 'Roteador TP-Link Wi-Fi 6'),
(839, 'Helena Santos', 'Microfone Condensador Redragon'),
(840, 'Nicolas Vieira', 'Impressora HP DeskJet'),
(841, 'Juliana Ferreira', 'Mesa Digitalizadora Wacom'),
(842, 'Isabela Souza', 'Gabinete ATX Gamer'),
(843, 'Oliveira Nascimento', 'Roteador TP-Link Wi-Fi 6'),
(844, 'Matheus Oliveira', 'Tablet Apple iPad'),
(845, 'Isabela Santos', 'Luminária de Mesa LED'),
(846, 'Igor Soares', 'SSD M.2 NVMe 1TB Kingston'),
(847, 'João Vieira', 'Monitor LG 29 Ultrawide'),
(848, 'João Dias', 'Placa Mãe Asus TUF'),
(849, 'Wagner Mendes', 'Notebook Dell Inspiron'),
(850, 'Felipe Lima', 'Microfone Condensador Redragon'),
(851, 'Ana Mendes', 'Webcam Logitech C920'),
(852, 'Eduardo Santos', 'SSD M.2 NVMe 1TB Kingston'),
(853, 'Caio Nascimento', 'Teclado Mecânico Logitech'),
(854, 'Daniela Oliveira', 'Smartphone Samsung Galaxy'),
(855, 'Carlos Gomes', 'SSD M.2 NVMe 1TB Kingston'),
(856, 'Mariana Rodrigues', 'Memória RAM 16GB DDR4'),
(857, 'Gustavo Ribeiro', 'Nobreak Intelbras 1200VA'),
(858, 'Isabela Martins', 'Nobreak Intelbras 1200VA'),
(859, 'Fernanda Dias', 'Gabinete ATX Gamer'),
(860, 'Igor Rocha', 'Hub USB-C 7 em 1'),
(861, 'Helena Ferreira', 'Impressora HP DeskJet'),
(862, 'Felipe Soares', 'Cadeira Ergonômica Flexform'),
(863, 'Patricia Silva', 'Memória RAM 16GB DDR4'),
(864, 'Bruno Gomes', 'Luminária de Mesa LED'),
(865, 'Heitor Fernandes', 'Nobreak Intelbras 1200VA'),
(866, 'Patricia Pereira', 'Luminária de Mesa LED'),
(867, 'Caio Rodrigues', 'Filtro de Linha 6 Tomadas'),
(868, 'Nicolas Mendes', 'Memória RAM 16GB DDR4'),
(869, 'Helena Santos', 'Placa Mãe Asus TUF'),
(870, 'Gustavo Barbosa', 'Memória RAM 16GB DDR4'),
(871, 'Bruno Pereira', 'Webcam Logitech C920'),
(872, 'Eduardo Souza', 'Carregador Indutivo Sem Fio'),
(873, 'Carlos Almeida', 'Carregador Indutivo Sem Fio'),
(874, 'Daniela Pereira', 'Placa de Vídeo RTX 3060'),
(875, 'Carlos Martins', 'Luminária de Mesa LED'),
(876, 'Patricia Fernandes', 'Webcam Logitech C920'),
(877, 'Daniela Rodrigues', 'Tablet Apple iPad'),
(878, 'Vanessa Pereira', 'Microfone Condensador Redragon'),
(879, 'Aline Vieira', 'Carregador Indutivo Sem Fio'),
(880, 'Aline Pereira', 'HD Externo Toshiba 1TB'),
(881, 'Juliana Dias', 'Tablet Apple iPad'),
(882, 'Patricia Carvalho', 'HD Externo Toshiba 1TB'),
(883, 'Thiago Santos', 'Impressora HP DeskJet'),
(884, 'Mariana Rocha', 'Gabinete ATX Gamer'),
(885, 'Heitor Fernandes', 'Smartphone Samsung Galaxy'),
(886, 'Daniela Ribeiro', 'Caixa de Som JBL Flip'),
(887, 'Elisa Soares', 'Mesa Digitalizadora Wacom'),
(888, 'Gustavo Carvalho', 'Cadeira Ergonômica Flexform'),
(889, 'Wagner Martins', 'Headset HyperX Cloud II'),
(890, 'Lara Pereira', 'Suporte para Notebook'),
(891, 'Wagner Nascimento', 'Cadeira Ergonômica Flexform'),
(892, 'João Santos', 'Impressora HP DeskJet'),
(893, 'Gustavo Carvalho', 'Impressora HP DeskJet'),
(894, 'Igor Martins', 'Suporte para Notebook'),
(895, 'Sofia Alves', 'Mesa Digitalizadora Wacom'),
(896, 'Fernanda Almeida', 'Hub USB-C 7 em 1'),
(897, 'Fernanda Fernandes', 'Placa de Vídeo RTX 3060'),
(898, 'Nicolas Santos', 'Filtro de Linha 6 Tomadas'),
(899, 'Elisa Dias', 'Carregador Indutivo Sem Fio'),
(900, 'Carlos Oliveira', 'Webcam Logitech C920'),
(901, 'Oliveira Lopes', 'Webcam Logitech C920'),
(902, 'Beatriz Gomes', 'Notebook Dell Inspiron'),
(903, 'Oliveira Alves', 'Placa de Vídeo RTX 3060'),
(904, 'Helena Mendes', 'Memória RAM 16GB DDR4'),
(905, 'Lara Pereira', 'Fonte Corsair 650W'),
(906, 'Oliveira Martins', 'Suporte para Notebook'),
(907, 'Aline Gomes', 'Nobreak Intelbras 1200VA'),
(908, 'João Fernandes', 'Caixa de Som JBL Flip'),
(909, 'Caio Gomes', 'Filtro de Linha 6 Tomadas'),
(910, 'Diego Soares', 'Smartphone Samsung Galaxy'),
(911, 'João Souza', 'Placa Mãe Asus TUF'),
(912, 'Lara Costa', 'Webcam Logitech C920'),
(913, 'Diego Costa', 'SSD M.2 NVMe 1TB Kingston'),
(914, 'Carlos Vieira', 'Suporte para Notebook'),
(915, 'Juliana Silva', 'Filtro de Linha 6 Tomadas'),
(916, 'Gustavo Gomes', 'Cadeira Ergonômica Flexform'),
(917, 'Nicolas Costa', 'Suporte para Notebook'),
(918, 'Elisa Vieira', 'Microfone Condensador Redragon'),
(919, 'Rafael Lopes', 'Impressora HP DeskJet'),
(920, 'Beatriz Lima', 'Memória RAM 16GB DDR4'),
(921, 'Matheus Mendes', 'Caixa de Som JBL Flip'),
(922, 'Matheus Almeida', 'Headset HyperX Cloud II'),
(923, 'Caio Ferreira', 'Cadeira Ergonômica Flexform'),
(924, 'Matheus Ferreira', 'Impressora HP DeskJet'),
(925, 'Daniela Soares', 'Monitor LG 29 Ultrawide'),
(926, 'Eduardo Dias', 'Monitor LG 29 Ultrawide'),
(927, 'Ana Carvalho', 'Cadeira Ergonômica Flexform'),
(928, 'Patricia Oliveira', 'Fonte Corsair 650W'),
(929, 'Juliana Silva', 'Webcam Logitech C920'),
(930, 'João Ribeiro', 'Monitor LG 29 Ultrawide'),
(931, 'Lara Dias', 'Smartphone Samsung Galaxy'),
(932, 'Bruno Silva', 'Impressora HP DeskJet'),
(933, 'Gustavo Silva', 'Notebook Dell Inspiron'),
(934, 'Thiago Fernandes', 'HD Externo Toshiba 1TB'),
(935, 'Bruno Soares', 'Microfone Condensador Redragon'),
(936, 'Heitor Ferreira', 'Mouse Sem Fio Dell'),
(937, 'Gabriel Soares', 'Cadeira Ergonômica Flexform'),
(938, 'Rafael Alves', 'Carregador Indutivo Sem Fio'),
(939, 'Sofia Ribeiro', 'Filtro de Linha 6 Tomadas'),
(940, 'Felipe Oliveira', 'Hub USB-C 7 em 1'),
(941, 'Felipe Almeida', 'Roteador TP-Link Wi-Fi 6'),
(942, 'Rafael Nascimento', 'Suporte para Notebook'),
(943, 'Wagner Dias', 'Microfone Condensador Redragon'),
(944, 'Fernanda Rocha', 'Caixa de Som JBL Flip'),
(945, 'Carlos Oliveira', 'Nobreak Intelbras 1200VA'),
(946, 'Elisa Martins', 'Impressora HP DeskJet'),
(947, 'Lara Santos', 'Caixa de Som JBL Flip'),
(948, 'Ana Nascimento', 'Headset HyperX Cloud II'),
(949, 'Fernanda Lopes', 'SSD M.2 NVMe 1TB Kingston'),
(950, 'Beatriz Vieira', 'Mouse Sem Fio Dell'),
(951, 'Carlos Pereira', 'Webcam Logitech C920'),
(952, 'Lara Lima', 'Monitor LG 29 Ultrawide'),
(953, 'Eduardo Dias', 'Filtro de Linha 6 Tomadas'),
(954, 'Carlos Ferreira', 'Mesa Digitalizadora Wacom'),
(955, 'Bruno Alves', 'Roteador TP-Link Wi-Fi 6'),
(956, 'Juliana Nascimento', 'Microfone Condensador Redragon'),
(957, 'Felipe Oliveira', 'HD Externo Toshiba 1TB'),
(958, 'Lucas Vieira', 'Suporte para Notebook'),
(959, 'Elisa Dias', 'Impressora HP DeskJet'),
(960, 'Beatriz Martins', 'Memória RAM 16GB DDR4'),
(961, 'Igor Nascimento', 'Placa de Vídeo RTX 3060'),
(962, 'Fernanda Soares', 'Placa de Vídeo RTX 3060'),
(963, 'Caio Santos', 'Mouse Sem Fio Dell'),
(964, 'Heitor Pereira', 'Microfone Condensador Redragon'),
(965, 'Eduardo Costa', 'Carregador Indutivo Sem Fio'),
(966, 'Felipe Costa', 'Notebook Dell Inspiron'),
(967, 'Thiago Almeida', 'Smartphone Samsung Galaxy'),
(968, 'Patricia Ribeiro', 'Impressora HP DeskJet'),
(969, 'Elisa Carvalho', 'Headset HyperX Cloud II'),
(970, 'Elisa Oliveira', 'Memória RAM 16GB DDR4'),
(971, 'Vanessa Pereira', 'Fonte Corsair 650W'),
(972, 'Eduardo Oliveira', 'Filtro de Linha 6 Tomadas'),
(973, 'Juliana Martins', 'Fonte Corsair 650W'),
(974, 'Juliana Mendes', 'Nobreak Intelbras 1200VA'),
(975, 'Aline Ribeiro', 'Mouse Sem Fio Dell'),
(976, 'Fernanda Silva', 'HD Externo Toshiba 1TB'),
(977, 'Isabela Ribeiro', 'Memória RAM 16GB DDR4'),
(978, 'Thiago Souza', 'Cadeira Ergonômica Flexform'),
(979, 'Fernanda Ferreira', 'SSD M.2 NVMe 1TB Kingston'),
(980, 'Isabela Fernandes', 'Impressora HP DeskJet'),
(981, 'Gustavo Souza', 'Notebook Dell Inspiron'),
(982, 'Fernanda Ribeiro', 'Impressora HP DeskJet'),
(983, 'Fernanda Barbosa', 'Carregador Indutivo Sem Fio'),
(984, 'Aline Martins', 'Notebook Dell Inspiron'),
(985, 'Vanessa Carvalho', 'Nobreak Intelbras 1200VA'),
(986, 'Fernanda Mendes', 'Impressora HP DeskJet'),
(987, 'Rafael Vieira', 'Tablet Apple iPad'),
(988, 'Lucas Dias', 'Nobreak Intelbras 1200VA'),
(989, 'Lucas Rodrigues', 'Filtro de Linha 6 Tomadas'),
(990, 'Wagner Lima', 'Smartphone Samsung Galaxy'),
(991, 'Juliana Oliveira', 'Headset HyperX Cloud II'),
(992, 'Heitor Lima', 'SSD M.2 NVMe 1TB Kingston'),
(993, 'Wagner Lopes', 'Placa Mãe Asus TUF'),
(994, 'Eduardo Ribeiro', 'Filtro de Linha 6 Tomadas'),
(995, 'Rafael Mendes', 'Caixa de Som JBL Flip'),
(996, 'Matheus Barbosa', 'Carregador Indutivo Sem Fio'),
(997, 'Nicolas Almeida', 'Mouse Sem Fio Dell'),
(998, 'Igor Gomes', 'Notebook Dell Inspiron'),
(999, 'Felipe Costa', 'Microfone Condensador Redragon'),
(1000, 'Elisa Costa', 'Luminária de Mesa LED');